services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
     - MONGODB_URI=mongodb://USERNAME:PASSWORD@domain-name:27017
     - REDIS_URI=redis://domain-name
     - ENABLE_WRITING_HANDLERS=false
