services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
     - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017
     - REDIS_URI=redis://redis:6379
     - ENABLE_WRITING_HANDLERS=false
    networks:
     - api-cache
     - database
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    networks:
     - api-cache
  
  mongodb:
    image: mongo:8.0-rc
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - data:/data/db
    networks:
      - database
      - express
      - seeding

  mongo-seeding:
    image: mongo:8.0-rc
    container_name: mongo-seeding
    volumes:
      - type: bind
        source: ./seeding.json
        target: /seeding.json
    networks:
      - seeding
    depends_on:
      - mongodb

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - express
    depends_on:
      - mongodb

networks:
   api-cache:
       external: true
       name: 'cache-network'
   database:
       external: true
       name: 'database-network'
   express:
       external: true
       name: 'express-network'
   seeding:
       external: true
       name: 'seeding-network'

volumes:
  data:

#Everything but seeding works; figure out production thing, profiles?
#Need some kind of command?
#express shuts off due to services not yet ready, find fix (maybe in past labs)