services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
     - MONGODB_URI=mongodb://USERNAME:PASSWORD@mongodb:27017
     - REDIS_URI=redis://redis:6379
     - ENABLE_WRITING_HANDLERS=false
    networks:
     - api-cache
     - database
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    networks:
     - api-cache
  
  mongodb:
    image: mongo:8.0-rc
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - database
      - express

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - express
    depends_on:
      - mongodb

networks:
   api-cache:
       external: true
       name: 'cache-network'
   database:
       external: true
       name: 'database-network'
   express:
       external: true
       name: 'express-network'
